//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zerohunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection_Logs
    {
        public int Id { get; set; }
        public int RequestId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<System.DateTime> Collection_date { get; set; }
        public Nullable<System.DateTime> Distribution_date { get; set; }
        public byte[] Distribution_status { get; set; }
    
        public virtual Collect_requests Collect_requests { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
